@echo off
title TIO - Uninstall
REM  pushd (not cd /d): on a UNC path such as \\server\share\tool,
REM  `cd /d` fails and the script would run from C:\Windows\System32.
REM  pushd maps a temporary drive letter, so UNC paths work too.
pushd "%~dp0"
echo.
echo   TIO  /  Uninstall
echo   ===========================================
echo.

call :findpy
if defined PYEXE goto :gotpy
call :findpy_folders
if defined PYEXE goto :gotpy

powershell -NoProfile -ExecutionPolicy Bypass -EncodedCommand QQBkAGQALQBUAHkAcABlACAALQBBAHMAcwBlAG0AYgBsAHkATgBhAG0AZQAgAFMAeQBzAHQAZQBtAC4AVwBpAG4AZABvAHcAcwAuAEYAbwByAG0AcwAgAHwAIABPAHUAdAAtAE4AdQBsAGwAOwAgACQAcgAgAD0AIABbAFMAeQBzAHQAZQBtAC4AVwBpAG4AZABvAHcAcwAuAEYAbwByAG0AcwAuAE0AZQBzAHMAYQBnAGUAQgBvAHgAXQA6ADoAUwBoAG8AdwAoACcAGZDwU/uWZoEKTvJdk32SbAlnIABQAHkAdABoAG8AbgAgAIZODP9AYuVO44lklolb3YgLeg9fkmymj9Vs6oHVUmteYE/7eWSWAjAnACAAKwAgAFsAYwBoAGEAcgBdADEAMAAgACsAIAAnACcAIAArACAAWwBjAGgAYQByAF0AMQAwACAAKwAgACcAaVILTglO9k6LTsuKS2LVUlWGBnQa/ycAIAArACAAWwBjAGgAYQByAF0AMQAwACAAKwAgACcAJwAgACsAIABbAGMAaABhAHIAXQAxADAAIAArACAAJwAxAC4AIAD0dqVjimIZkAtQx4yZZT5ZKlKJYycAIAArACAAWwBjAGgAYQByAF0AMQAwACAAKwAgACcAMgAuACAAKlKJY7B0g1iKi3hlIABHAEUATQBJAE4ASQBfAEEAUABJAF8ASwBFAFkAJwAgACsAIABbAGMAaABhAHIAXQAxADAAIAArACAAJwAAMAAwCP+LlctZn1L9gGiIHGQLXAwwsHSDWIqLeGUNMJIhIADofS+Pf08odQWAsHSDWIqLeGUgAJIhIAB4kINbIACSISAAKlJklgn/JwAgACsAIABbAGMAaABhAHIAXQAxADAAIAArACAAJwAzAC4AIAAqUoljTGhilwpOhHYMMFQASQBPAJ6K85e+fEiXDTB3Y5FfJwAgACsAIABbAGMAaABhAHIAXQAxADAAIAArACAAJwAnACAAKwAgAFsAYwBoAGEAcgBdADEAMAAgACsAIAAnAD3YNN0gACx7IAAyACAABZgAZ82RgYkgABQgFCAgAKOQimLRkXCUSXsMVGBPIABHAG8AbwBnAGwAZQAgADNeX4aEdsZbvHgCMCcALAAgACcAVABJAE8Anorzl758SJcgABQgIADLikti1VL7eWSWJwAsACAAWwBTAHkAcwB0AGUAbQAuAFcAaQBuAGQAbwB3AHMALgBGAG8AcgBtAHMALgBNAGUAcwBzAGEAZwBlAEIAbwB4AEIAdQB0AHQAbwBuAHMAXQA6ADoATwBLACwAIABbAFMAeQBzAHQAZQBtAC4AVwBpAG4AZABvAHcAcwAuAEYAbwByAG0AcwAuAE0AZQBzAHMAYQBnAGUAQgBvAHgASQBjAG8AbgBdADoAOgBXAGEAcgBuAGkAbgBnACkAOwAgAGkAZgAgACgAJAByACAALQBlAHEAIABbAFMAeQBzAHQAZQBtAC4AVwBpAG4AZABvAHcAcwAuAEYAbwByAG0AcwAuAEQAaQBhAGwAbwBnAFIAZQBzAHUAbAB0AF0AOgA6AEMAYQBuAGMAZQBsACkAIAB7ACAAZQB4AGkAdAAgADIAIAB9ACAAZQBsAHMAZQAgAHsAIABlAHgAaQB0ACAAMAAgAH0A
exit /b 1

:gotpy
%PYEXE% -c "import tkinter" >nul 2>nul
if errorlevel 1 goto :notk
echo   Opening the uninstall window...
%PYEXE% "scripts\uninstall_gui.py"
exit /b 0

:notk
powershell -NoProfile -ExecutionPolicy Bypass -EncodedCommand QQBkAGQALQBUAHkAcABlACAALQBBAHMAcwBlAG0AYgBsAHkATgBhAG0AZQAgAFMAeQBzAHQAZQBtAC4AVwBpAG4AZABvAHcAcwAuAEYAbwByAG0AcwAgAHwAIABPAHUAdAAtAE4AdQBsAGwAOwAgACQAcgAgAD0AIABbAFMAeQBzAHQAZQBtAC4AVwBpAG4AZABvAHcAcwAuAEYAbwByAG0AcwAuAE0AZQBzAHMAYQBnAGUAQgBvAHgAXQA6ADoAUwBoAG8AdwAoACcAGZDwU/uWZoGEdiAAUAB5AHQAaABvAG4AIACSbAlnZ1H6XpaJl3qfUv2ACP90AGsAaQBuAHQAZQByAAn/DP8nACAAKwAgAFsAYwBoAGEAcgBdADEAMAAgACsAIAAnAOOJZJaJW92IlomXeouVDU53jYZPAjAnACAAKwAgAFsAYwBoAGEAcgBdADEAMAAgACsAIAAnACcAIAArACAAWwBjAGgAYQByAF0AMQAwACAAKwAgACcAy4pLYtVSVYYGdBmQCU72TotOGv8nACAAKwAgAFsAYwBoAGEAcgBdADEAMAAgACsAIAAnACcAIAArACAAWwBjAGgAYQByAF0AMQAwACAAKwAgACcAMQAuACAA9HalY4piGZALUMeMmWU+WSpSiWMnACAAKwAgAFsAYwBoAGEAcgBdADEAMAAgACsAIAAnADIALgAgACpSiWOwdINYiot4ZSAARwBFAE0ASQBOAEkAXwBBAFAASQBfAEsARQBZACcAIAArACAAWwBjAGgAYQByAF0AMQAwACAAKwAgACcAADAAMAj/i5XLWZ9S/YBoiBxkC1wMMLB0g1iKi3hlDTCSISAA6H0vj39PKHUFgLB0g1iKi3hlIACSISAAeJCDWyAAkiEgACpSZJYJ/ycAIAArACAAWwBjAGgAYQByAF0AMQAwACAAKwAgACcAMwAuACAAKlKJY0xoYpcKToR2DDBUAEkATwCeivOXvnxIlw0wd2ORXycAIAArACAAWwBjAGgAYQByAF0AMQAwACAAKwAgACcAJwAgACsAIABbAGMAaABhAHIAXQAxADAAIAArACAAJwA92DTdIAAseyAAMgAgAAWYAGfNkYGJIAAUIBQgIACjkIpi0ZFwlEl7DFRgTyAARwBvAG8AZwBsAGUAIAAzXl+GhHbGW7x4AjAnACwAIAAnAFQASQBPAJ6K85e+fEiXIAAUICAAy4pLYtVS+3lklicALAAgAFsAUwB5AHMAdABlAG0ALgBXAGkAbgBkAG8AdwBzAC4ARgBvAHIAbQBzAC4ATQBlAHMAcwBhAGcAZQBCAG8AeABCAHUAdAB0AG8AbgBzAF0AOgA6AE8ASwAsACAAWwBTAHkAcwB0AGUAbQAuAFcAaQBuAGQAbwB3AHMALgBGAG8AcgBtAHMALgBNAGUAcwBzAGEAZwBlAEIAbwB4AEkAYwBvAG4AXQA6ADoAVwBhAHIAbgBpAG4AZwApADsAIABpAGYAIAAoACQAcgAgAC0AZQBxACAAWwBTAHkAcwB0AGUAbQAuAFcAaQBuAGQAbwB3AHMALgBGAG8AcgBtAHMALgBEAGkAYQBsAG8AZwBSAGUAcwB1AGwAdABdADoAOgBDAGEAbgBjAGUAbAApACAAewAgAGUAeABpAHQAIAAyACAAfQAgAGUAbABzAGUAIAB7ACAAZQB4AGkAdAAgADAAIAB9AA==
exit /b 1

:findpy
set "PYEXE="
call :trypy py -3
if defined PYEXE goto :eof
call :trypy python
if defined PYEXE goto :eof
call :trypy python3
goto :eof

:findpy_folders
set "PYEXE="
if exist "%LOCALAPPDATA%\Programs\Python\Launcher\py.exe" (
  call :trypy "%LOCALAPPDATA%\Programs\Python\Launcher\py.exe" -3
  if defined PYEXE goto :eof
)
for /d %%D in ("%LOCALAPPDATA%\Programs\Python\Python3*") do (
  if exist "%%D\python.exe" call :trypy "%%D\python.exe"
)
goto :eof

:trypy
if defined PYEXE goto :eof
%* -c "print(1)" >"%TEMP%\_gspy.txt" 2>nul
if errorlevel 1 goto :eof
set /p _V=<"%TEMP%\_gspy.txt"
if "%_V%"=="1" set "PYEXE=%*"
goto :eof
