@echo off
title TIO - Setup
REM  pushd (not cd /d): on a UNC path such as \\server\share\tool,
REM  `cd /d` fails and the script would run from C:\Windows\System32.
REM  pushd maps a temporary drive letter, so UNC paths work too.
pushd "%~dp0"
echo.
echo   TIO
echo   ===========================================
echo.

REM ======================================================================
REM  Stage 1 : make sure a REAL Python exists.
REM
REM  Do NOT use "where python": Windows ships a 0-byte Microsoft Store
REM  alias at WindowsApps\python.exe, so "where" succeeds even with NO
REM  Python installed. We must actually RUN it and check it prints.
REM ======================================================================
call :findpy
if defined PYEXE goto :gotpy

echo   Python is not installed on this computer.
echo.

REM --- ask for consent via a PowerShell dialog -------------
powershell -NoProfile -ExecutionPolicy Bypass -EncodedCommand QQBkAGQALQBUAHkAcABlACAALQBBAHMAcwBlAG0AYgBsAHkATgBhAG0AZQAgAFMAeQBzAHQAZQBtAC4AVwBpAG4AZABvAHcAcwAuAEYAbwByAG0AcwAgAHwAIABPAHUAdAAtAE4AdQBsAGwAOwAgACQAcgAgAD0AIABbAFMAeQBzAHQAZQBtAC4AVwBpAG4AZABvAHcAcwAuAEYAbwByAG0AcwAuAE0AZQBzAHMAYQBnAGUAQgBvAHgAXQA6ADoAUwBoAG8AdwAoACcAUAB5AHQAaABvAG4AIABpAHMAIABuAG8AdAAgAGkAbgBzAHQAYQBsAGwAZQBkACAAbwBuACAAdABoAGkAcwAgAGMAbwBtAHAAdQB0AGUAcgAgAHkAZQB0ACwAIABhAG4AZAAgAHQAaABpAHMAIAB0AG8AbwBsACAAbgBlAGUAZABzACAAaQB0ACAAdABvACAAcgB1AG4ALgAnACAAKwAgAFsAYwBoAGEAcgBdADEAMAAgACsAIAAnACcAIAArACAAWwBjAGgAYQByAF0AMQAwACAAKwAgACcAUAByAGUAcwBzACAAIgBPAEsAIgAgAGEAbgBkACAAaQB0ACAAdwBpAGwAbAAgAGIAZQAgAGkAbgBzAHQAYQBsAGwAZQBkACAAYQB1AHQAbwBtAGEAdABpAGMAYQBsAGwAeQAuACAAVABoAGkAcwAgAHQAYQBrAGUAcwAgAGEAYgBvAHUAdAAgADEAEyAzACAAbQBpAG4AdQB0AGUAcwAuACcAIAArACAAWwBjAGgAYQByAF0AMQAwACAAKwAgACcAVwBoAGkAbABlACAAaQB0ACAAaQBuAHMAdABhAGwAbABzACwAIAB0AGUAeAB0ACAAawBlAGUAcABzACAAcwBjAHIAbwBsAGwAaQBuAGcAIABpAG4AIAB0AGgAZQAgAGIAbABhAGMAawAgAHcAaQBuAGQAbwB3AC4AIABUAGgAYQB0ACAAaQBzACAAbgBvAHIAbQBhAGwAOwAgAHAAbABlAGEAcwBlACAAZABvACAAbgBvAHQAIABjAGwAbwBzAGUAIABpAHQALgAnACAAKwAgAFsAYwBoAGEAcgBdADEAMAAgACsAIAAnACcAIAArACAAWwBjAGgAYQByAF0AMQAwACAAKwAgACcAIiAgAEkAdAAgAGkAcwAgAGkAbgBzAHQAYQBsAGwAZQBkACAAdQBuAGQAZQByACAAeQBvAHUAcgAgAG8AdwBuACAAdQBzAGUAcgAgAGEAYwBjAG8AdQBuAHQAOwAgAG4AbwAgAGEAZABtAGkAbgBpAHMAdAByAGEAdABvAHIAIAByAGkAZwBoAHQAcwAgAGEAcgBlACAAbgBlAGUAZABlAGQAJwAgACsAIABbAGMAaABhAHIAXQAxADAAIAArACAAJwAiICAATgBvACAAbwB0AGgAZQByACAAcwBlAHQAdABpAG4AZwBzACAAbwBuACAAdABoAGkAcwAgAGMAbwBtAHAAdQB0AGUAcgAgAGEAcgBlACAAYwBoAGEAbgBnAGUAZAAnACAAKwAgAFsAYwBoAGEAcgBdADEAMAAgACsAIAAnACIgIABTAGUAdAB1AHAAIABjAGEAcgByAGkAZQBzACAAbwBuACAAYgB5ACAAaQB0AHMAZQBsAGYAIABhAGYAdABlAHIAdwBhAHIAZABzADsAIAB5AG8AdQAgAGQAbwAgAG4AbwB0ACAAbgBlAGUAZAAgAHQAbwAgAGMAbABpAGMAawAgAGEAZwBhAGkAbgAnACAAKwAgAFsAYwBoAGEAcgBdADEAMAAgACsAIAAnACcAIAArACAAWwBjAGgAYQByAF0AMQAwACAAKwAgACcAQwBvAG4AdABpAG4AdQBlAD8AJwAsACAAJwBUAEkATwAgAFYAbwBpAGMAZQAgAEcAZQBuAGkAZQAgABQgIABQAHkAdABoAG8AbgAgAGkAcwAgAG4AZQBlAGQAZQBkACAAZgBpAHIAcwB0ACcALAAgAFsAUwB5AHMAdABlAG0ALgBXAGkAbgBkAG8AdwBzAC4ARgBvAHIAbQBzAC4ATQBlAHMAcwBhAGcAZQBCAG8AeABCAHUAdAB0AG8AbgBzAF0AOgA6AE8ASwBDAGEAbgBjAGUAbAAsACAAWwBTAHkAcwB0AGUAbQAuAFcAaQBuAGQAbwB3AHMALgBGAG8AcgBtAHMALgBNAGUAcwBzAGEAZwBlAEIAbwB4AEkAYwBvAG4AXQA6ADoAUQB1AGUAcwB0AGkAbwBuACkAOwAgAGkAZgAgACgAJAByACAALQBlAHEAIABbAFMAeQBzAHQAZQBtAC4AVwBpAG4AZABvAHcAcwAuAEYAbwByAG0AcwAuAEQAaQBhAGwAbwBnAFIAZQBzAHUAbAB0AF0AOgA6AEMAYQBuAGMAZQBsACkAIAB7ACAAZQB4AGkAdAAgADIAIAB9ACAAZQBsAHMAZQAgAHsAIABlAHgAaQB0ACAAMAAgAH0A
if errorlevel 2 goto :userquit

where winget >nul 2>nul
if errorlevel 1 goto :nowinget

echo   -----------------------------------------------------------
echo    STEP 1 of 2 : Installing Python   (1-3 minutes, please wait)
echo    Text will scroll by. That is normal. Do NOT close this window.
echo   -----------------------------------------------------------
echo.
winget install --id Python.Python.3.13 -e --scope user --accept-source-agreements --accept-package-agreements
set "WGRC=%ERRORLEVEL%"
echo.
echo   STEP 1 finished. Locating the Python that was just installed...

REM --- 1) plain PATH lookup (usually still stale in this window) --------
call :findpy
if defined PYEXE goto :gotpy

REM --- 2) refresh PATH from the registry, then look again ---------------
for /f "tokens=2,*" %%A in ('reg query "HKCU\Environment" /v PATH 2^>nul') do set "NEWPATH=%%B"
if defined NEWPATH set "PATH=%PATH%;%NEWPATH%"
call :findpy
if defined PYEXE goto :gotpy

REM --- 3) go straight to where winget puts it (--scope user) ------------
call :findpy_folders
if defined PYEXE goto :gotpy

REM --- 4) still nothing. Which message depends on whether winget worked.
REM     Getting this wrong is worse than useless: telling someone
REM     "Python is installed, just click again" when the install actually
REM     FAILED sends them round in circles.
if not "%WGRC%"=="0" goto :manualpy
powershell -NoProfile -ExecutionPolicy Bypass -EncodedCommand QQBkAGQALQBUAHkAcABlACAALQBBAHMAcwBlAG0AYgBsAHkATgBhAG0AZQAgAFMAeQBzAHQAZQBtAC4AVwBpAG4AZABvAHcAcwAuAEYAbwByAG0AcwAgAHwAIABPAHUAdAAtAE4AdQBsAGwAOwAgACQAcgAgAD0AIABbAFMAeQBzAHQAZQBtAC4AVwBpAG4AZABvAHcAcwAuAEYAbwByAG0AcwAuAE0AZQBzAHMAYQBnAGUAQgBvAHgAXQA6ADoAUwBoAG8AdwAoACcAUAB5AHQAaABvAG4AIABpAHMAIABpAG4AcwB0AGEAbABsAGUAZAAgAG4AbwB3ACwAIABiAHUAdAAgAHQAaABpAHMAIAB3AGkAbgBkAG8AdwAgAGMAYQBuAG4AbwB0ACAAcwBlAGUAIABpAHQAIAB5AGUAdAAuACcAIAArACAAWwBjAGgAYQByAF0AMQAwACAAKwAgACcAJwAgACsAIABbAGMAaABhAHIAXQAxADAAIAArACAAJwBQAGwAZQBhAHMAZQAgAGMAbABvAHMAZQAgAHQAaABpAHMAIABiAGwAYQBjAGsAIAB3AGkAbgBkAG8AdwAgAGEAbgBkACAAZABvAHUAYgBsAGUALQBjAGwAaQBjAGsAIAAiADMAXwBJAG4AcwB0AGEAbABsAC4AYgBhAHQAIgAgAG8AbgBjAGUAIABtAG8AcgBlAC4AJwAgACsAIABbAGMAaABhAHIAXQAxADAAIAArACAAJwAoAFQAaABpAHMAIABvAG4AbAB5ACAAaABhAHAAcABlAG4AcwAgAHQAaABpAHMAIABvAG4AZQAgAHQAaQBtAGUALgApACcALAAgACcAVABJAE8AIABWAG8AaQBjAGUAIABHAGUAbgBpAGUAIAAUICAAcABsAGUAYQBzAGUAIAByAHUAbgAgAHMAZQB0AHUAcAAgAGEAZwBhAGkAbgAnACwAIABbAFMAeQBzAHQAZQBtAC4AVwBpAG4AZABvAHcAcwAuAEYAbwByAG0AcwAuAE0AZQBzAHMAYQBnAGUAQgBvAHgAQgB1AHQAdABvAG4AcwBdADoAOgBPAEsALAAgAFsAUwB5AHMAdABlAG0ALgBXAGkAbgBkAG8AdwBzAC4ARgBvAHIAbQBzAC4ATQBlAHMAcwBhAGcAZQBCAG8AeABJAGMAbwBuAF0AOgA6AEkAbgBmAG8AcgBtAGEAdABpAG8AbgApADsAIABpAGYAIAAoACQAcgAgAC0AZQBxACAAWwBTAHkAcwB0AGUAbQAuAFcAaQBuAGQAbwB3AHMALgBGAG8AcgBtAHMALgBEAGkAYQBsAG8AZwBSAGUAcwB1AGwAdABdADoAOgBDAGEAbgBjAGUAbAApACAAewAgAGUAeABpAHQAIAAyACAAfQAgAGUAbABzAGUAIAB7ACAAZQB4AGkAdAAgADAAIAB9AA==
exit /b 1

REM ======================================================================
REM  Stage 2 : hand over to the graphical setup wizard.
REM ======================================================================
:gotpy
echo.
echo   [OK] Python: %PYEXE%
echo.
echo   -----------------------------------------------------------
echo    STEP 2 of 2 : Opening the setup window...
echo    A window will appear in a moment. Continue there.
echo   -----------------------------------------------------------
%PYEXE% -c "import tkinter" >nul 2>nul
if errorlevel 1 goto :textmode
%PYEXE% "scripts\setup_gui.py"
exit /b 0

:textmode
powershell -NoProfile -ExecutionPolicy Bypass -EncodedCommand QQBkAGQALQBUAHkAcABlACAALQBBAHMAcwBlAG0AYgBsAHkATgBhAG0AZQAgAFMAeQBzAHQAZQBtAC4AVwBpAG4AZABvAHcAcwAuAEYAbwByAG0AcwAgAHwAIABPAHUAdAAtAE4AdQBsAGwAOwAgACQAcgAgAD0AIABbAFMAeQBzAHQAZQBtAC4AVwBpAG4AZABvAHcAcwAuAEYAbwByAG0AcwAuAE0AZQBzAHMAYQBnAGUAQgBvAHgAXQA6ADoAUwBoAG8AdwAoACcAVABoAGUAIABQAHkAdABoAG8AbgAgAG8AbgAgAHQAaABpAHMAIABjAG8AbQBwAHUAdABlAHIAIABoAGEAcwAgAG4AbwAgAGIAdQBpAGwAdAAtAGkAbgAgAHcAaQBuAGQAbwB3ACAAcwB1AHAAcABvAHIAdAAgACgAdABrAGkAbgB0AGUAcgApACwAJwAgACsAIABbAGMAaABhAHIAXQAxADAAIAArACAAJwBzAG8AIAB0AGgAZQAgAFMAZQB0AHUAcAAgAFcAaQB6AGEAcgBkACAAdwBpAG4AZABvAHcAIABjAGEAbgBuAG8AdAAgAG8AcABlAG4ALgAnACAAKwAgAFsAYwBoAGEAcgBdADEAMAAgACsAIAAnACcAIAArACAAWwBjAGgAYQByAF0AMQAwACAAKwAgACcAVABoAGEAdAAgAGkAcwAgAGYAaQBuAGUAOgAgAHMAZQB0AHUAcAAgAHcAaQBsAGwAIABjAG8AbgB0AGkAbgB1AGUAIABpAG4AIAB0AGUAeAB0ACAAbQBvAGQAZQAuACAAVABoAGUAIABtAGEAaQBuACAAcwB0AGUAcABzACAAYQByAGUAIAB0AGgAZQAgAHMAYQBtAGUALAAgAGIAdQB0ACAAbgBvACAAZABlAHMAawB0AG8AcAAgAHMAaABvAHIAdABjAHUAdAAgAGkAcwAgAGMAcgBlAGEAdABlAGQAIAAoAGEAZgB0AGUAcgB3AGEAcgBkAHMALAAgAGoAdQBzAHQAIABkAG8AdQBiAGwAZQAtAGMAbABpAGMAawAgADQAXwBTAHQAYQByAHQALgBiAGEAdAAgAGkAbgAgAHQAaABlACAAZgBvAGwAZABlAHIAKQAsACAAYQBuAGQAIABpAGYAIABhAG4AIABvAGYAZgBpAGMAZQAgAG4AZQB0AHcAbwByAGsAIABpAG4AdABlAHIAYwBlAHAAdABzACAAYwBlAHIAdABpAGYAaQBjAGEAdABlAHMALAAgAGkAdAAgAHcAaQBsAGwAIABuAG8AdAAgAHIAZQB0AHIAeQAgAGEAdQB0AG8AbQBhAHQAaQBjAGEAbABsAHkALgAnACAAKwAgAFsAYwBoAGEAcgBdADEAMAAgACsAIAAnAEoAdQBzAHQAIABhAG4AcwB3AGUAcgAgAHQAaABlACAAcQB1AGUAcwB0AGkAbwBuAHMAIABpAG4AIAB0AGgAZQAgAGIAbABhAGMAawAgAHcAaQBuAGQAbwB3AC4AJwAsACAAJwBUAEkATwAgAFYAbwBpAGMAZQAgAEcAZQBuAGkAZQAgABQgIABzAHcAaQB0AGMAaABpAG4AZwAgAHQAbwAgAHQAZQB4AHQALQBtAG8AZABlACAAcwBlAHQAdQBwACcALAAgAFsAUwB5AHMAdABlAG0ALgBXAGkAbgBkAG8AdwBzAC4ARgBvAHIAbQBzAC4ATQBlAHMAcwBhAGcAZQBCAG8AeABCAHUAdAB0AG8AbgBzAF0AOgA6AE8ASwAsACAAWwBTAHkAcwB0AGUAbQAuAFcAaQBuAGQAbwB3AHMALgBGAG8AcgBtAHMALgBNAGUAcwBzAGEAZwBlAEIAbwB4AEkAYwBvAG4AXQA6ADoASQBuAGYAbwByAG0AYQB0AGkAbwBuACkAOwAgAGkAZgAgACgAJAByACAALQBlAHEAIABbAFMAeQBzAHQAZQBtAC4AVwBpAG4AZABvAHcAcwAuAEYAbwByAG0AcwAuAEQAaQBhAGwAbwBnAFIAZQBzAHUAbAB0AF0AOgA6AEMAYQBuAGMAZQBsACkAIAB7ACAAZQB4AGkAdAAgADIAIAB9ACAAZQBsAHMAZQAgAHsAIABlAHgAaQB0ACAAMAAgAH0A
%PYEXE% "scripts\setup.py"
exit /b 0

REM ======================================================================
REM  Failure paths
REM ======================================================================
:nowinget
powershell -NoProfile -ExecutionPolicy Bypass -EncodedCommand QQBkAGQALQBUAHkAcABlACAALQBBAHMAcwBlAG0AYgBsAHkATgBhAG0AZQAgAFMAeQBzAHQAZQBtAC4AVwBpAG4AZABvAHcAcwAuAEYAbwByAG0AcwAgAHwAIABPAHUAdAAtAE4AdQBsAGwAOwAgACQAcgAgAD0AIABbAFMAeQBzAHQAZQBtAC4AVwBpAG4AZABvAHcAcwAuAEYAbwByAG0AcwAuAE0AZQBzAHMAYQBnAGUAQgBvAHgAXQA6ADoAUwBoAG8AdwAoACcAVABoAGkAcwAgAGMAbwBtAHAAdQB0AGUAcgAgAGQAbwBlAHMAIABuAG8AdAAgAGgAYQB2AGUAIAB3AGkAbgBnAGUAdAAsACAAdABoAGUAIABhAHUAdABvAG0AYQB0AGkAYwAgAGkAbgBzAHQAYQBsAGwAIAB0AG8AbwBsACAAZgBvAHIAIABXAGkAbgBkAG8AdwBzACwAJwAgACsAIABbAGMAaABhAHIAXQAxADAAIAArACAAJwBzAG8AIABQAHkAdABoAG8AbgAgAGMAYQBuAG4AbwB0ACAAYgBlACAAaQBuAHMAdABhAGwAbABlAGQAIABmAG8AcgAgAHkAbwB1ACAAYQB1AHQAbwBtAGEAdABpAGMAYQBsAGwAeQAuACcAIAArACAAWwBjAGgAYQByAF0AMQAwACAAKwAgACcAJwAgACsAIABbAGMAaABhAHIAXQAxADAAIAArACAAJwBUAGgAZQAgAG8AZgBmAGkAYwBpAGEAbAAgAFAAeQB0AGgAbwBuACAAZABvAHcAbgBsAG8AYQBkACAAcABhAGcAZQAgAHcAaQBsAGwAIABvAHAAZQBuACAAbgBlAHgAdAAuACAAUABsAGUAYQBzAGUAIABmAG8AbABsAG8AdwAgAHQAaABlAHMAZQAgAHQAaAByAGUAZQAgAHMAdABlAHAAcwA6ACcAIAArACAAWwBjAGgAYQByAF0AMQAwACAAKwAgACcAJwAgACsAIABbAGMAaABhAHIAXQAxADAAIAArACAAJwAxAC4AIABEAG8AdwBuAGwAbwBhAGQAIABhAG4AZAAgAHIAdQBuACAAdABoAGUAIABQAHkAdABoAG8AbgAgAGkAbgBzAHQAYQBsAGwAZQByACcAIAArACAAWwBjAGgAYQByAF0AMQAwACAAKwAgACcAMgAuACAAPdg03SAATwBuACAAdABoAGUAIABpAG4AcwB0AGEAbABsAGUAcgAgAHMAYwByAGUAZQBuACwAIAB0AGgAZQAgACIAQQBkAGQAIABwAHkAdABoAG8AbgAuAGUAeABlACAAdABvACAAUABBAFQASAAiACAAYgBvAHgAIABhAHQAIAB0AGgAZQAgAHYAZQByAHkAIABiAG8AdAB0AG8AbQAgAE0AVQBTAFQAIABiAGUAIAB0AGkAYwBrAGUAZAAnACAAKwAgAFsAYwBoAGEAcgBdADEAMAAgACsAIAAnADMALgAgAFcAaABlAG4AIABpAHQAIABoAGEAcwAgAGYAaQBuAGkAcwBoAGUAZAAsACAAYwBvAG0AZQAgAGIAYQBjAGsAIABhAG4AZAAgAGQAbwB1AGIAbABlAC0AYwBsAGkAYwBrACAAIgAzAF8ASQBuAHMAdABhAGwAbAAuAGIAYQB0ACIAIABhAGcAYQBpAG4AJwAsACAAJwBUAEkATwAgAFYAbwBpAGMAZQAgAEcAZQBuAGkAZQAgABQgIABwAGwAZQBhAHMAZQAgAGkAbgBzAHQAYQBsAGwAIABQAHkAdABoAG8AbgAgAGIAeQAgAGgAYQBuAGQAJwAsACAAWwBTAHkAcwB0AGUAbQAuAFcAaQBuAGQAbwB3AHMALgBGAG8AcgBtAHMALgBNAGUAcwBzAGEAZwBlAEIAbwB4AEIAdQB0AHQAbwBuAHMAXQA6ADoATwBLACwAIABbAFMAeQBzAHQAZQBtAC4AVwBpAG4AZABvAHcAcwAuAEYAbwByAG0AcwAuAE0AZQBzAHMAYQBnAGUAQgBvAHgASQBjAG8AbgBdADoAOgBXAGEAcgBuAGkAbgBnACkAOwAgAGkAZgAgACgAJAByACAALQBlAHEAIABbAFMAeQBzAHQAZQBtAC4AVwBpAG4AZABvAHcAcwAuAEYAbwByAG0AcwAuAEQAaQBhAGwAbwBnAFIAZQBzAHUAbAB0AF0AOgA6AEMAYQBuAGMAZQBsACkAIAB7ACAAZQB4AGkAdAAgADIAIAB9ACAAZQBsAHMAZQAgAHsAIABlAHgAaQB0ACAAMAAgAH0A
start "" "https://www.python.org/downloads/"
exit /b 1

:manualpy
powershell -NoProfile -ExecutionPolicy Bypass -EncodedCommand QQBkAGQALQBUAHkAcABlACAALQBBAHMAcwBlAG0AYgBsAHkATgBhAG0AZQAgAFMAeQBzAHQAZQBtAC4AVwBpAG4AZABvAHcAcwAuAEYAbwByAG0AcwAgAHwAIABPAHUAdAAtAE4AdQBsAGwAOwAgACQAcgAgAD0AIABbAFMAeQBzAHQAZQBtAC4AVwBpAG4AZABvAHcAcwAuAEYAbwByAG0AcwAuAE0AZQBzAHMAYQBnAGUAQgBvAHgAXQA6ADoAUwBoAG8AdwAoACcAUAB5AHQAaABvAG4AIABjAG8AdQBsAGQAIABuAG8AdAAgAGIAZQAgAGkAbgBzAHQAYQBsAGwAZQBkACAAYQB1AHQAbwBtAGEAdABpAGMAYQBsAGwAeQAuACcAIAArACAAWwBjAGgAYQByAF0AMQAwACAAKwAgACcAJwAgACsAIABbAGMAaABhAHIAXQAxADAAIAArACAAJwBUAGgAZQAgAG8AZgBmAGkAYwBpAGEAbAAgAFAAeQB0AGgAbwBuACAAZABvAHcAbgBsAG8AYQBkACAAcABhAGcAZQAgAHcAaQBsAGwAIABvAHAAZQBuACAAZgBvAHIAIAB5AG8AdQAgAG4AZQB4AHQALgAgAFAAbABlAGEAcwBlACAAZgBvAGwAbABvAHcAIAB0AGgAZQBzAGUAIAB0AGgAcgBlAGUAIABzAHQAZQBwAHMAOgAnACAAKwAgAFsAYwBoAGEAcgBdADEAMAAgACsAIAAnACcAIAArACAAWwBjAGgAYQByAF0AMQAwACAAKwAgACcAMQAuACAARABvAHcAbgBsAG8AYQBkACAAYQBuAGQAIAByAHUAbgAgAHQAaABlACAAUAB5AHQAaABvAG4AIABpAG4AcwB0AGEAbABsAGUAcgAnACAAKwAgAFsAYwBoAGEAcgBdADEAMAAgACsAIAAnADIALgAgAD3YNN0gAE8AbgAgAHQAaABlACAAaQBuAHMAdABhAGwAbABlAHIAIABzAGMAcgBlAGUAbgAsACAAdABoAGUAIAAiAEEAZABkACAAcAB5AHQAaABvAG4ALgBlAHgAZQAgAHQAbwAgAFAAQQBUAEgAIgAgAGIAbwB4ACAAYQB0ACAAdABoAGUAIAB2AGUAcgB5ACAAYgBvAHQAdABvAG0AIABNAFUAUwBUACAAYgBlACAAdABpAGMAawBlAGQAJwAgACsAIABbAGMAaABhAHIAXQAxADAAIAArACAAJwAzAC4AIABXAGgAZQBuACAAaQB0ACAAaABhAHMAIABmAGkAbgBpAHMAaABlAGQALAAgAGMAbwBtAGUAIABiAGEAYwBrACAAYQBuAGQAIABkAG8AdQBiAGwAZQAtAGMAbABpAGMAawAgACIAMwBfAEkAbgBzAHQAYQBsAGwALgBiAGEAdAAiACAAYQBnAGEAaQBuACcAIAArACAAWwBjAGgAYQByAF0AMQAwACAAKwAgACcAJwAgACsAIABbAGMAaABhAHIAXQAxADAAIAArACAAJwBJAGYAIAB5AG8AdQByACAAbwByAGcAYQBuAGkAcwBhAHQAaQBvAG4AIABkAG8AZQBzACAAbgBvAHQAIABhAGwAbABvAHcAIAB5AG8AdQAgAHQAbwAgAGkAbgBzAHQAYQBsAGwAIABzAG8AZgB0AHcAYQByAGUAIAB5AG8AdQByAHMAZQBsAGYALAAgAHAAbABlAGEAcwBlACAAYQBzAGsAIAB5AG8AdQByACAASQBUACAAcwB0AGEAZgBmACAAZgBvAHIAIABoAGUAbABwAC4AJwAsACAAJwBUAEkATwAgAFYAbwBpAGMAZQAgAEcAZQBuAGkAZQAgABQgIABwAGwAZQBhAHMAZQAgAGkAbgBzAHQAYQBsAGwAIABQAHkAdABoAG8AbgAgAGIAeQAgAGgAYQBuAGQAJwAsACAAWwBTAHkAcwB0AGUAbQAuAFcAaQBuAGQAbwB3AHMALgBGAG8AcgBtAHMALgBNAGUAcwBzAGEAZwBlAEIAbwB4AEIAdQB0AHQAbwBuAHMAXQA6ADoATwBLACwAIABbAFMAeQBzAHQAZQBtAC4AVwBpAG4AZABvAHcAcwAuAEYAbwByAG0AcwAuAE0AZQBzAHMAYQBnAGUAQgBvAHgASQBjAG8AbgBdADoAOgBXAGEAcgBuAGkAbgBnACkAOwAgAGkAZgAgACgAJAByACAALQBlAHEAIABbAFMAeQBzAHQAZQBtAC4AVwBpAG4AZABvAHcAcwAuAEYAbwByAG0AcwAuAEQAaQBhAGwAbwBnAFIAZQBzAHUAbAB0AF0AOgA6AEMAYQBuAGMAZQBsACkAIAB7ACAAZQB4AGkAdAAgADIAIAB9ACAAZQBsAHMAZQAgAHsAIABlAHgAaQB0ACAAMAAgAH0A
start "" "https://www.python.org/downloads/"
exit /b 1

:userquit
echo   Cancelled by user.
exit /b 0

REM ======================================================================
REM  Helpers
REM ======================================================================
:findpy
set "PYEXE="
call :trypy py -3
if defined PYEXE goto :eof
call :trypy python
if defined PYEXE goto :eof
call :trypy python3
goto :eof

:findpy_folders
set "PYEXE="
if exist "%LOCALAPPDATA%\Programs\Python\Launcher\py.exe" (
  call :trypy "%LOCALAPPDATA%\Programs\Python\Launcher\py.exe" -3
  if defined PYEXE goto :eof
)
for /d %%D in ("%LOCALAPPDATA%\Programs\Python\Python3*") do (
  if exist "%%D\python.exe" call :trypy "%%D\python.exe"
)
if defined PYEXE goto :eof
for /d %%D in ("%ProgramFiles%\Python3*") do (
  if exist "%%D\python.exe" call :trypy "%%D\python.exe"
)
goto :eof

:trypy
if defined PYEXE goto :eof
%* -c "print(1)" >"%TEMP%\_gspy.txt" 2>nul
if errorlevel 1 goto :eof
set /p _V=<"%TEMP%\_gspy.txt"
if "%_V%"=="1" set "PYEXE=%*"
goto :eof
